# Missing Value Distributions

```{r, echo=FALSE,warning=FALSE, message=FALSE}
library(tidyverse)
#install.packages("pak")
#pak::pak("thiyangt/vegetablesSriLanka")
library("vegetablesSriLanka")
library(knitr)
library(plotly)
library(GGally)
library(patchwork)
library(lubridate)
library(tsibble)
library(feasts)
library(fable)
library(fabletools)
```


```{r, echo=FALSE, warning=FALSE, message=FALSE, fig.width=18, fig.height=10}
vegetables.srilanka <- vegetables.srilanka |>
  mutate( Item = factor(Item, levels = c("Beans",
                                   "Big Onion (Imp)",
                                   "Brinjal",
                                   "Cabbage",
                                   "Carrot",
                                   "Green Chilli",
                                   "Lime",
                                   "Potato (Imp)",
                                   "Pumpkin",
                                   "Snake gourd",
                                   "Tomato",
                                   "Potato (Local)",
                                   "Big Onion (Local)", "Red Onion (Imp)",
                                   "Red Onion (Local)"))) 

```

```{r, echo=FALSE}
#vegetables.srilanka |>
#  as_tsibble(key = c(Item, Type, Market),
#    index = Date) |>
#  scan_gaps()

vegetables_long_tsibble <- vegetables.srilanka |>
  as_tsibble(key = c(Item, Type, Market),
    index = Date) 
```

```{r, echo=FALSE}
veg_filled <- vegetables_long_tsibble |>
  group_by_key() |>
  fill_gaps() |>
  ungroup() |>
  as_tsibble() |>
  mutate(Year = year(Date))
```

## Dambulla



### Dambulla: Wholesale Price


```{r, echo=FALSE, fig.width=10, fig.height=10}
missing_summary_dw <- veg_filled |>
  as_tibble() |>
  filter(Type == "Wholesale", Market == "Dambulla") |>
  filter(!is.na(Item)) |>
  select(Item, Price, Year) |>
  group_by(Item, Year) |>
  summarise(
    missing_pct = mean(is.na(Price)) * 100,  # check missing only in Price
    .groups = "drop"
  ) |>
  mutate(Period = if_else(Year < 2022, "Before 2022", "2022 and After"))
```

```{r, echo=FALSE, fig.width=10, fig.height=10}


ggplot(missing_summary_dw, aes(x = factor(Year), y = missing_pct,
                           fill=Period))+
  geom_bar(stat = "identity") +
  geom_text(
    aes(label = round(missing_pct, 1)),
    vjust = 0.9,
    size = 3
  ) +
  facet_wrap(~ Item, ncol = 4, nrow = 4, scales = "free_y")  +
  labs(
    x = "Year",
    y = "Missing Percentage (%)"
  ) +
  scale_fill_brewer(palette = "Set2") +
  theme(
    axis.text.x = element_text(angle = 90, hjust = 1),
    strip.text = element_text(face = "bold"),
    legend.position = "bottom"
  )
```


### Dambulla: Retail Price

```{r, echo=FALSE, fig.width=10, fig.height=10}
missing_summary <- veg_filled |>
  as_tibble() |>
  filter(Type == "Retail", Market == "Dambulla") |>
  filter(!is.na(Item)) |>
  select(Item, Price, Year) |>
  group_by(Item, Year) |>
  summarise(
    missing_pct = mean(is.na(Price)) * 100,  # check missing only in Price
    .groups = "drop"
  ) |>
  mutate(Period = if_else(Year < 2022, "Before 2022", "2022 and After"))
```

```{r, echo=FALSE,fig.width=10, fig.height=10}


ggplot(missing_summary, aes(x = factor(Year), y = missing_pct,
                           fill=Period))+
  geom_bar(stat = "identity") +
  geom_text(
    aes(label = round(missing_pct, 1)),
    vjust = 0.9,
    size = 3
  ) +
  facet_wrap(~ Item, ncol = 4, nrow = 4, scales = "free_y")  +
  labs(
    x = "Year",
    y = "Missing Percentage (%)"
  ) +
  scale_fill_brewer(palette = "Set2") +
  theme(
    axis.text.x = element_text(angle = 90, hjust = 1),
    strip.text = element_text(face = "bold"),
    legend.position = "bottom"
  )
```



## Pettah

### Pettah: Wholesale Price


```{r, echo=FALSE, fig.width=10, fig.height=10}
missing_summary <- veg_filled |>
  as_tibble() |>
  filter(Type == "Wholesale", Market == "Pettah") |>
  filter(!is.na(Item)) |>
  select(Item, Price, Year) |>
  group_by(Item, Year) |>
  summarise(
    missing_pct = mean(is.na(Price)) * 100,  # check missing only in Price
    .groups = "drop"
  ) |>
  mutate(Period = if_else(Year < 2022, "Before 2022", "2022 and After"))
```

```{r, echo=FALSE, fig.width=10, fig.height=10}


ggplot(missing_summary, aes(x = factor(Year), y = missing_pct,
                           fill=Period))+
  geom_bar(stat = "identity") +
  geom_text(
    aes(label = round(missing_pct, 1)),
    vjust = 0.9,
    size = 3
  ) +
  facet_wrap(~ Item, ncol = 4, nrow = 4, scales = "free_y")  +
  labs(
    x = "Year",
    y = "Missing Percentage (%)"
  ) +
  scale_fill_brewer(palette = "Set2") +
  theme(
    axis.text.x = element_text(angle = 90, hjust = 1),
    strip.text = element_text(face = "bold"),
    legend.position = "bottom"
  )
```




### Pettah: Retail Price


```{r, echo=FALSE, fig.width=10, fig.height=10}
missing_summary <- veg_filled |>
  as_tibble() |>
  filter(Type == "Retail", Market == "Pettah") |>
  filter(!is.na(Item)) |>
  select(Item, Price, Year) |>
  group_by(Item, Year) |>
  summarise(
    missing_pct = mean(is.na(Price)) * 100,  # check missing only in Price
    .groups = "drop"
  ) |>
  mutate(Period = if_else(Year < 2022, "Before 2022", "2022 and After"))
```

```{r, echo=FALSE, fig.width=10, fig.height=10}


ggplot(missing_summary, aes(x = factor(Year), y = missing_pct,
                           fill=Period))+
  geom_bar(stat = "identity") +
  geom_text(
    aes(label = round(missing_pct, 1)),
    vjust = 0.9,
    size = 3
  ) +
  facet_wrap(~ Item, ncol = 4, nrow = 4, scales = "free_y")  +
  labs(
    x = "Year",
    y = "Missing Percentage (%)"
  ) +
  scale_fill_brewer(palette = "Set2") +
  theme(
    axis.text.x = element_text(angle = 90, hjust = 1),
    strip.text = element_text(face = "bold"),
    legend.position = "bottom"
  )
```

